cargo-features = ["edition2024"]
[package]
name = "geppetto-derive"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
geppetto-parser = { path = "../parser" }
pinocchio = "0.8.4"